#!/usr/bin/env python3

import logging
import sys
import time
import traceback

from feed_proxy import db
from feed_proxy.config import get_config_storage
from feed_proxy.proxies import Proxy
from feed_proxy.utils import make_logger, CompactFormatter

log_fmt = '%(asctime)s:%(levelname)s:%(name)s:%(message)s'
handler = logging.StreamHandler(sys.stdout)
handler.setFormatter(CompactFormatter(log_fmt, "%Y-%m-%d %H:%M:%S"))
logger = make_logger('feed_proxy', handler=handler, level='INFO')

start = time.time()

try:
    logger.info('FeedProxy server started')
    db.init()

    config_storage = get_config_storage()

    proxy = Proxy(config_storage)
    proxy.run()
except Exception:
    traceback.print_exc()
    logger.critical('FeedProxy terminated abnormally')
else:
    logger.info('FeedProxy terminated normally')

minutes = (time.time() - start) / 60
logger.info(f'It took {minutes:0.0f} minutes.')
