#!/usr/bin/env python3

from feed_proxy import db
from feed_proxy.config import get_config_storage
from feed_proxy.proxies import Proxy

db.init()

config_storage = get_config_storage()

proxy = Proxy(config_storage)
proxy.run()
